name: gauravvohra
favicon: null
layout_spectrum: 0.5180049871560186
typography_spectrum: 0.4165799298789352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8084049571771175
  lightness: 0.48340195207856596
  saturation: 0.8962322410661727
  rhythmicContrast: 0.06930447742342949
purpose: []
